//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modalfirst_ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerID { get; set; }
        public string customerName { get; set; }
        public int customerAge { get; set; }
        public string customerPhone { get; set; }
        public string customerPW { get; set; }
        public int employe_employeID { get; set; }
    }
}
