//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modalfirst_ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe
    {
        public int employeID { get; set; }
        public string employeName { get; set; }
        public int employeAge { get; set; }
        public int employeWope { get; set; }
        public string employePhone { get; set; }
        public string employePW { get; set; }
    }
}
