//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modalfirst_ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class home
    {
        public int homeID { get; set; }
        public string homeName { get; set; }
        public string homeAdres { get; set; }
        public int homePrice { get; set; }
        public int homeM2 { get; set; }
        public int customer_customerID { get; set; }
    }
}
