//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modalfirst_ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class plot
    {
        public int plotID { get; set; }
        public string plotName { get; set; }
        public string plotAdres { get; set; }
        public int plotPrice { get; set; }
        public int plotM2 { get; set; }
        public int customer_customerID { get; set; }
    }
}
